In [6]:
import tensorflow as tf
import numpy as np
x = tf.constant(5, name = 'constant')
y = tf.Variable(x**2, name = 'variable')
print(y)

<tf.Variable 'variable_1:0' shape=() dtype=int32_ref>


In [15]:
model = tf.global_variables_initializer()
with tf.Session() as sess:
    out=sess.run(model)
    print(out)
    print(sess.run(y))

None
25


In [13]:
tf_tensor = tf.placeholder(tf.float32, shape=(4,4))
x = np.arange(16).reshape(4,4)
with tf.Session() as sess:
    out = sess.run(tf_tensor, feed_dict={tf_tensor: x})
    print(out)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [16]:
%matplotlib inline

In [ ]:
import matplotlib.image as mp_image
filename = 